# n8n Docker Compose configuration for use with nginx proxy manager
# Configured to work with standalone nginx proxy manager setup
# Uses SQLite database (default)

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"  # Only expose to localhost - nginx proxy manager will handle external access
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - npm_default

volumes:
  n8n_data:
    external: false

networks:
  npm_default:
    external: true  # Use the existing nginx proxy manager network
