services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.${DOMAIN}`)"
      - "traefik.http.routers.linkwarden.entrypoints=websecure"
      - "traefik.http.routers.linkwarden.tls.certresolver=cloudflare"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
    networks:
      - proxy_connect
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3004:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres

networks:
  proxy_connect:
    external: true
