services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--tls.certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--tls.certificatesresolvers.myresolver.acme.email=kaustubh@kaustubhsstuff.com"
      - "--tls.certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
     - "443:443"
     - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  letsencrypt: