services:
  maybe:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - app-storage:/rails/storage
    ports:
      - 3002:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maybe.rule=Host(`maybe.${DOMAIN}`)"
      - "traefik.http.routers.maybe.entrypoints=websecure"
      - "traefik.http.routers.maybe.tls.certresolver=cloudflare"
      - "traefik.http.services.maybe.loadbalancer.server.port=3000"
    restart: unless-stopped
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      DB_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    networks:
      - proxy_connect
      - internal_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
      POSTGRES_DB: ${POSTGRES_DB:-maybe_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal_network

volumes:
  app-storage:
  postgres-data:


networks:
  proxy_connect:
    external: true
  internal_network:
    name: maybe_internal
    internal: true
