services:
  glance:
    container_name: glance
    image: glanceapp/glance
    ports:
      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host('kaustubhsstuff.com')"
    volumes:
      - ./config:/app/config
      - letsencrypt:/app/letsencrypt

volumes:
  letsencrypt: