services:
  
  glance:
    container_name: glance
    image: glanceapp/glance
    ports:
      - "8081:8080"
    labels:
      - "traefik.http.routers.glance.rule=Host(`glance.kaustubhsstuff.com`)"
      - "traefik.http.services.glance.loadbalancer.server.port=8081"
    volumes:
      - ./config:/app/config
      - letsencrypt:/app/letsencrypt

volumes:
  letsencrypt: