services:
  meet_portfolio:
    image: ghcr.io/kaustubhtrivedi/meet-portfolio:latest
    container_name: meet_portfolio
    restart: unless-stopped
    ports:
      - 4173:4173
    networks:
      - proxy_connect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meet_portfolio.rule=Host(`meetport.kaustubhsstuff.com`)"
      - "traefik.http.routers.meet_portfolio.tls.certresolver=cloudflare"
      - "traefik.http.routers.meet_portfolio.entrypoints=websecure"
      - "traefik.http.routers.meet_portfolio.tls=true"
      - "traefik.http.services.meet_portfolio.loadbalancer.server.port=4173"

networks:
  proxy_connect:
    external: true
