services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true" # Enable dashboard
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Don't expose containers by deault
      - "--entrypoints.web.address=:80" # HTTP entry point
      - "--entrypoints.websecure.address=:443" # HTTPS entry point
      - "--entrypoints.websecure.http.tls=true" # Enable TLS on HTTPS
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true" # DNS challenge for certs
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare" # Cloudflare DNS provider
      - "--certificatesresolvers.cloudflare.acme.email=kaus12tri@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`traefik.${MYDOMAIN}`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    ports:
      - "80:80" # Expose HTTP (Cloudflare forwards this)
      - "443:443" # Expose HTTPS (Cloudflare forwards this)
    environment:
      - CF_API_EMAIL=kaus12tri@gmail.com # Cloudflare account email
      - CF_API_KEY=${CF_API_KEY} # Cloudflare Global API Key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Docker provider
      - "./letsencrypt:/letsencrypt" # Let's Encrypt storage
