services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      - "--log.level=DEBUG" # Enable debug logging
      - "--api=true" # Enable API explicitly
      - "--api.dashboard=true"
      - "--api.insecure=true" # For testing only
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.web.proxyProtocol.insecure"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Expose dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/var/log/traefik"
      - "traefik-certificates:/certificates"
    networks:
      - proxy_connect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.kaustubhsstuff.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # Dashboard router configuration
      - "traefik.http.routers.api.rule=Host(`traefik.kaustubhsstuff.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"

volumes:
  traefik-certificates:


networks:
  proxy_connect:
    external: true
