services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - proxy_connect

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`tandoor.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=7000"
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - proxy_connect

networks:
  proxy_connect:
    external: true

volumes:
  staticfiles:
